//AUTH STATE
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//ALERT STATE
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_ERRORS = 'GET_ERRORS';

//CHANGE PASSWORD STATE
export const REQUEST_CHANGE_PASSWORD = "REQUEST_CHANGE_PASSWORD";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

//USER STATES
export const CREATE_USER = "CREATE_USER";
export const NEW_USER_ADDED = "NEW_USER_ADDED";
export const REQUEST_ALL_USERS = "REQUEST_ALL_USERS";
export const LIST_ALL_USERS = "LIST_ALL_USERS";
export const REQUEST_DELETE_USER = "REQUEST_DELETE_USER";
export const USER_DELETED = "USER_DELETED";

//PRODUCT STATE
export const PRODUCT_ADDED = 'PRODUCT_ADDED';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_LOADED = 'GET_PRODUCT_LOADED';
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_LOADED = 'GET_ALL_PRODUCTS_LOADED';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED'
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';

//CHECKOUT STATE
export const PRODUCT_ADDED_TO_BASKET = 'PRODUCT_ADDED_TO_BASKET';
export const PRODUCT_UPDATED_TO_BASKET = 'PRODUCT_UPDATED_TO_BASKET';
export const PRODUCT_BASKET_QUANTITY_UPDATED = 'PRODUCT_BASKET_QUANTITY_UPDATED';
export const PRODUCT_REMOVED_FROM_BASKET = 'PRODUCT_REMOVED_FROM_BASKET';
export const FINALISE_CHECKOUT = 'FINALISE_CHECKOUT';
export const CHECKOUT_FAIL = 'CHECKOUT_FAIL'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CANCEL_CHECKOUT = 'CANCEL_CHECKOUT';

//INVOICE STATE
export const LOADING_ALL_INVOICE = "LOADING_ALL_INVOICE";
export const LOAD_ALL_INVOICE = "LOAD_ALL_INVOICE";
export const LOAD_ALL_INVOICE_FAIL = "LOAD_ALL_INVOICE_FAIL"
export const GETTING_INVOICE = "GETTING_INVOICE"
export const GET_INVOICE = "GET INVOICE"
export const GET_INVOICE_FAIL = "GET_INVOICE_FAIL"
export const GETTING_INVOICE_ITEM = "GETTING_INVOICE_ITEM"
export const GET_INVOICE_ITEM = "GET_INVOICE_ITEM"
export const GET_INVOICE_ITEM_FAIL = "GET_INVOICE_ITEM_FAIL"
export const RETURNING_ITEM = "RETURNING_ITEM"
export const ITEM_RETURNED = "ITEM_RETURNED"
export const RETURN_ITEM_FAILED = "RETURN_ITEM_FAILED"
export const FINALISING_RETURN = "FINALISING_RETURN"
export const RETURN_FINALISED = "RETURN_FINALISED"
export const FINALISE_RETURN_FAILED = "FINALISE_RETURN_FAILED"

